name: "dbt_analytics_eng_cert"

config-version: 2
version: "1.0.0"

profile: "default"

# Where dbt looks for different resource types

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Where compiled artifacts are written

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Default model behavior

models:
  dbt_analytics_eng_cert:
    +database: |
      {%- if target.name | lower | trim == 'development' -%}
        DBT_ANALYTICS_ENG_CERT_DEV
      {%- elif target.name | lower | trim  == 'staging' -%}
        DBT_ANALYTICS_ENG_CERT_RC
      {%- else -%}
        DBT_ANALYTICS_ENG_CERT
      {%- endif -%}
      
    stg: 
      snowflake_sample_data:
        +materialized: view
        +schema: staging
        # +materialized: incremental 
        # +incremental_strategy: merge
        # +unique_key: merge_key
        # +on_schema_change: append_new_columns 
        # +partition_by:
          # - dbt_updated_at
        # +exclude: 
          # - dbt_synced_at
